version: 2
jobs:
  safety:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build image
          command: "docker build -t panda_safety -f tests/safety/Dockerfile ."
      - run:
          name: Run safety test
          command: |
            docker run panda_safety /bin/bash -c "cd /panda/tests/safety; PYTHONPATH=/ ./test.sh"

  misra-c2012:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build image
          command: "docker build -t panda_misra -f tests/misra/Dockerfile ."
      - run:
          name: Run Misra C 2012 test
          command: |
            mkdir /tmp/misra
            docker run -v /tmp/misra:/tmp/misra panda_misra /bin/bash -c "cd /panda/tests/misra; ./test_misra.sh"
      - store_artifacts:
          name: Store cppcheck test output
          path: /tmp/misra/cppcheck_output.txt
      - store_artifacts:
          name: Store misra test output
          path: /tmp/misra/misra_output.txt

  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build image
          command: "docker build -t panda_build -f tests/build/Dockerfile ."
      - run:
          name: Test python package installer
          command: |
            docker run panda_build /bin/bash -c "cd /panda; python setup.py install"
      - run:
          name: Build Panda STM image
          command: |
            docker run panda_build /bin/bash -c "cd /panda/board; make bin"
      - run:
          name: Build Panda STM bootstub image
          command: |
            docker run panda_build /bin/bash -c "cd /panda/board; make obj/bootstub.panda.bin"
      - run:
          name: Build Pedal STM image
          command: |
            docker run panda_build /bin/bash -c "cd /panda/board/pedal; make obj/comma.bin"
      - run:
          name: Build Pedal STM bootstub image
          command: |
            docker run panda_build /bin/bash -c "cd /panda/board/pedal; make obj/bootstub.bin"
      - run:
          name: Build ESP image
          command: |
            docker run panda_build /bin/bash -c "cd /panda/boardesp; make user1.bin"

  safety_replay:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build image
          command: "docker build -t panda_safety_replay -f tests/safety_replay/Dockerfile ."
      - run:
          name: Replay drives
          command: |
            docker run panda_safety_replay /bin/bash -c "cd /openpilot/panda/tests/safety_replay; PYTHONPATH=/openpilot ./test_safety_replay.py"

  language_check:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build image
          command: "docker build -t language_check -f tests/language/Dockerfile ."
      - run:
          name: Check code for bad language
          command: |
            docker run language_check /bin/bash -c "cd /panda/tests/language; ./test_language.py"

workflows:
  version: 2
  main:
    jobs:
      - safety
      - misra-c2012
      - build
      - safety_replay
      - language_check
