sudo: required

services:
  - docker

install:
  - docker build -t tmppilot -f Dockerfile.openpilot .

script:
  - docker run --rm
      -v "$(pwd)"/selfdrive/test/tests/plant/out:/tmp/openpilot/selfdrive/test/tests/plant/out
      tmppilot /bin/sh -c 'cd /tmp/openpilot/selfdrive/test/tests/plant && OPTEST=1 ./test_longitudinal.py'
