name: 'compile openpilot'

runs:
  using: "composite"
  steps:
    - shell: bash
      name: Build openpilot with all flags
      run: |
        source .venv/bin/activate
        scons -j$(nproc)
        release/check-dirty.sh
    - shell: bash
      name: Cleanup scons cache and rebuild
      run: |
        source .venv/bin/activate
        rm -rf .ci_cache/scons_cache/* && \
        scons -j$(nproc) --cache-populate
    - name: Save scons cache
      uses: actions/cache/save@v4
      if: github.ref == 'refs/heads/master'
      with:
        path: .ci_cache/scons_cache
        key: scons-${{ runner.arch }}-${{ env.CACHE_COMMIT_DATE }}-${{ github.sha }}
