name: 'compile openpilot'

runs:
  using: "composite"
  steps:
    - shell: bash
      name: Build openpilot with all flags
      run: |
        ${{ env.RUN }} "scons -j$(nproc)"
        ${{ env.RUN }} "release/check-dirty.sh"
    - shell: bash
      name: Cleanup scons cache and rebuild
      run: |
          ${{ env.RUN }} "rm -rf /tmp/scons_cache/* && \
                          scons -j$(nproc) --cache-populate"
    - name: Save scons cache
      uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      if: github.ref == 'refs/heads/master'
      with:
        path: .ci_cache/scons_cache
        key: scons-${{ runner.arch }}-${{ env.CACHE_COMMIT_DATE }}-${{ github.sha }}
