site_name: openpilot docs
docs_dir: docs
repo_url: https://github.com/commaai/openpilot/
site_url: https://docs.comma.ai

strict: true

theme:
  name: terminal
  features:
    - navigation.side.toc.hide

nav:
  - Getting Started:
    - What is openpilot?: getting-started/what-is-openpilot.md
  - How-to:
    #- Make my first pull request: how-to/first-pr.md
    - Connect to a comma 3/3X: how-to/connect-to-comma.md
  - Car Porting:
    - What is a car port?: car-porting/what-is-a-car-port.md
    - Porting a car brand: car-porting/brand-port.md
    - Porting a car model: car-porting/model-port.md
  - Contributing:
    - Roadmap: contributing/roadmap.md
    #- Architecture: contributing/architecture.md
    - Contributing: https://github.com/commaai/openpilot/blob/master/docs/CONTRIBUTING.md
  - Links:
    - Blog: https://blog.comma.ai
    - Bounties: https://comma.ai/bounties
    - GitHub: https://github.com/commaai
    - Discord: https://discord.comma.ai
    - X: https://x.com/comma_ai
