# on Windows -- $env:SKIP="tests,example"
repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: python3 -m ruff check .
        language: system
        always_run: true
        pass_filenames: false
      - id: tiny
        name: tiny tests
        entry: python3 -m pytest test/test_tiny.py
        language: system
        always_run: true
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: python3 -m mypy tinygrad/ --strict-equality
        language: system
        always_run: true
        pass_filenames: false
      - id: example
        name: test all devices
        entry: python3 test/external/external_test_example.py
        language: system
        always_run: true
        pass_filenames: false
      - id: tests
        name: subset of tests
        entry: env OMP_NUM_THREADS=1 PYTHONPATH="." python3 -m pytest -n=6 test/test_ops.py test/test_dtype.py test/test_schedule.py test/test_assign.py
        language: system
        always_run: true
        pass_filenames: false
