name: release
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build_masterci:
    name: build master-ci
    env:
      TARGET_DIR: /tmp/openpilot
      ImageOS: ubuntu20
    container:
      image: ghcr.io/commaai/openpilot-base:latest
    runs-on: ubuntu-20.04
    if: github.repository == 'commaai/openpilot'
    steps:
    - name: Install wait-on-check-action dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libyaml-dev
    - name: Wait for green check mark
      if: ${{ github.event_name != 'workflow_dispatch' }}
      uses: lewagon/wait-on-check-action@e2558238c09778af25867eb5de5a3ce4bbae3dcd
      with:
        ref: master
        wait-interval: 30
        running-workflow-name: 'build master-ci'
        check-regexp: ^((?!.*(build prebuilt).*).)*$
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0
    - name: Pull LFS
      run: |
        git config --global --add safe.directory '*'
        git lfs pull
    - name: Build master-ci
      run: |
        release/build_devel.sh
    - name: Run tests
      run: |
        export PYTHONPATH=$TARGET_DIR
        cd $TARGET_DIR
        scons -j$(nproc)
        selfdrive/car/tests/test_car_interfaces.py
    - name: Push master-ci
      run: |
        unset TARGET_DIR
        BRANCH=master-ci release/build_devel.sh
